### ISSUE TITLE
Build and publish individual npm packages for each YUI module

### ISSUE THREAD

**Issue by unkillbob** [yui/grunt-yui-contrib#16] opened 2014-03-10 08:51 UTC
YUI is currently pretty heavyweight for using inside Node.js primarily because you have to pull down the entire library even if you just want to use a few utilities. It'd be really great to be able to depend on just a select few YUI modules e.g.

``` bash
$ npm install yui.handlebars yui.template-base --save
```

``` js
var Handlebars = require('yui.handlebars').Handlebars,
    Template = require('yui.template-base').Template;

new Template(Handlebars).precompile('Wish I could do {{this}}.');
```

This is particularly useful in a few build tooling situations (such as precompiling templates) where it would be great to not have the entire 40mb YUI distro (and the time it takes to npm install it) when all you need is `template-base`, `template-micro` and `handlebars` (and their dependencies).

Naively this doesn't seem like it'd be too hard (and I'm keen to tackle it myself if that's cool) - I was just wondering if there was any existing plans to do this, reasons it hasn't been done or prior art elsewhere?

I had a look around the various YUI repos for an existing issue, wasn't sure if this was the right place to raise this, let me know if I should relocate it.

**Comment by caridy** [comment] 2014-03-10 14:58
@unkillbob we have been thinking about this for a while, @davglass wanted to do it more than a year ago, but we never did it. Instead, we are slowly approaching the point where those small tools can be extracted from the actually library, and they could be re-assemble back into the library distro (a la ypromise).

The good news is, the mighty @tivac has been working on a new project that may cover this very well, here is the repo:

https://github.com/tivac/yui-clumper

Let me know if that helps, so we can probably work with @tivac on defining a list of pkgs that we will like to push to npm on every release.

**Comment by unkillbob** [comment] 2014-03-10 19:04
@caridy @tivac yui-clumper may be just what I need, my particular use case is for the template precompilation (so I'd need `template-base`, `template-micro` and `handlebars`). It would also be good to slim down [yuidoc](https://github.com/yui/yuidoc) which also depends on the full yui module, though I'm not sure what it uses it for or whether it'd be possible to depend on just part of yui for its use cases.

This issue might still be useful for you then? I assume you'd want to run `clumper` over several collections of modules as part of the release build.

**Comment by tivac** [comment] 2014-03-10 19:17
Uh oh, somebody noticed https://github.com/tivac/yui-clumper!

Clumper was specifically built because I want to precompile `Template.Micro` templates as part of our build process w/o checking in the entire YUI library. It's not quite there yet, as it needs more tests & actually generated useful `package.json` files for the modules it spits out. I'd love some help finishing it though! I'm swamped right now w/ work and won't be able to work on it for a bit but will definitely review/merge PRs.

**Comment by unkillbob** [comment] 2014-03-10 19:20
@tivac if I find some time I'll send you a PR or two, pretty busy myself but this is something we're pretty keen on (for similar reasons). I assume I can just pick up one of the issues on the repo?

**Comment by tivac** [comment] 2014-03-10 19:21
@unkillbob Yeah, those're the only remaining pieces it needs AFAIK. Of course, since I haven't actually _tried_ running the modules it spits out in Node there may be some surprises lurking.

**Comment by tivac** [comment] 2014-03-11 07:06
Found some time to work on clumper tonight, should be more or less fully-functional now. It's also up on [NPM](https://www.npmjs.org/package/yui-clumper) now.

**Comment by tivac** [comment] 2014-03-11 07:06
Though it should be noted: it still **really** needs more tests.

**Comment by unkillbob** [comment] 2014-03-17 22:21
Awesome thanks @tivac! So what needs to happen next for this to be a reality?

**Comment by tivac** [comment] 2014-03-17 22:33
Someone needs to run it & generate YUI packages for modules (& preferably put them on NPM). I don't want to be listed as the owner for a bunch of YUI code on NPM, so I'm not going to be publishing it.

Alternatively you could export the modules you cared about & then just check them into your app/private NPM repo & start using them.

Currently it uses a hardcoded YUI version from `package.json` & an interesting PR would be making the tool able to go download a user-specified version of YUI from NPM & generating packages based on that.

**Comment by ericf** [comment] 2014-03-19 16:41
I don't think this is the right approach. I feel that Lodash doing this is a mistake. I think this would pollute npm. Like @caridy is saying, we'd rather extract stuff from YUI and publish that as its own package.

What's on the list besides `Template.Micro`?

**Comment by unkillbob** [comment] 2014-03-19 18:54
> we'd rather extract stuff from YUI and publish that as its own package

@ericf is that not what clumper enables? I'd envision an extra step in the grunt tasks etc that publishes some of the few modules that make sense on their own (initially just Y.Template).

**Comment by caridy** [comment] 2014-03-19 19:05
I think this should be a manual process, I mean, pushing to NPM each individual pkg when needed, and using clumper to help you set up that pkg, and probably adding some extra stuff to it, like `index.js` to expose `Y.Template` directly instead of just exposing `Y`, more a la nodejs.

I volunteer myself to create a couple of them, and see how it goes. I'm closing this issue since this doesn't belong to this repo for the reasons @ericf mentioned.

**Closed as completed by caridy** 2014-03-19 19:05 UTC

**Comment by tivac** [comment] 2014-03-19 19:25
> and probably adding some extra stuff to it, like index.js to expose Y.Template directly instead of just exposing Y, more a la nodejs.

IIRC Clumper does this, and if not it definitely should & will.

**Comment by caridy** [comment] 2014-03-19 19:28
@tivac the problem is, how will Clumper knows about the namespace to export? unless you pass it as an argument, in which case I do agree!

**Comment by tivac** [comment] 2014-03-19 19:31
@caridy I'm probably misunderstanding the request then. :disappointed: 

Once there's a process in place file issues for any parts of it that should be automated (all of them, IMO) and we can get it sorted out. Clumper's really simple so adding useful functionality should be straight-forward.

**Comment by caridy** [comment] 2014-03-19 19:37
@tivac I was talking about something like this:

```
clumper foo -o output -n yui-foo -f raw --NS FooBar
```

which basically means:

```
module.exports = require('yui/foo').FooBar;
```

Probably easy to do as you said.
